export const PRIMARY_COLOR = '#fff'; // Brand Color
export const PRIMARY_DARK_COLOR = '';
export const ACCENT_COLOR = '#000'; // Tint color of icons and higlights
export const BACKGROUND_COLOR = '#F7F6F4'; // Background color for page
export const BORDER_COLOR = '#eaecf1';
export const TRANSPARENT_COLOR = '#00000000';
export const DEFAULT_TEXT_COLOR = '#757575';
export const SUCCESS_TEXT_COLOR = 'green'; // Change it
export const ERROR_TEXT_COLOR = 'red'; // change it
